# Generated by Django 5.0 on 2023-12-22 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('idVoo', models.AutoField(primary_key=True, serialize=False)),
                ('volumeinicialAgua', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pressaoInicial', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pesoFoguete', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pressaoBomba', models.DecimalField(decimal_places=2, max_digits=6)),
                ('anguloLancamento', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Instante',
            fields=[
                ('idInstante', models.AutoField(primary_key=True, serialize=False)),
                ('tempo', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('altitude', models.DecimalField(decimal_places=2, max_digits=6)),
                ('idVoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foguete.voo')),
            ],
        ),
    ]
